<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Paise;

class PaiseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Paise::create(['code' => 'AF','name' => 'AFGANISTÁN']);
        Paise::create(['code' => 'AL','name' => 'ALBANIA']);
        Paise::create(['code' => 'DE','name' => 'ALEMANIA']);
        Paise::create(['code' => 'AD','name' => 'ANDORRA']);
        Paise::create(['code' => 'AO','name' => 'ANGOLA']);
        Paise::create(['code' => 'AI','name' => 'ANGUILA']);
        Paise::create(['code' => 'AQ','name' => 'ANTÁRTIDA']);
        Paise::create(['code' => 'AG','name' => 'ANTIGUA Y BARBUDA']);
        Paise::create(['code' => 'AN','name' => 'ANTILLAS NEERLANDESAS']);
        Paise::create(['code' => 'SA','name' => 'ARABIA SAUDÍ']);
        Paise::create(['code' => 'DZ','name' => 'ARGELIA']);
        Paise::create(['code' => 'AR','name' => 'ARGENTINA']);
        Paise::create(['code' => 'AM','name' => 'ARMENIA']);
        Paise::create(['code' => 'AW','name' => 'ARUBA']);
        Paise::create(['code' => 'AU','name' => 'AUSTRALIA']);
        Paise::create(['code' => 'AT','name' => 'AUSTRIA']);
        Paise::create(['code' => 'AZ','name' => 'AZERBAIYÁN']);
        Paise::create(['code' => 'BS','name' => 'BAHAMAS']);
        Paise::create(['code' => 'BH','name' => 'BAHRÉIN']);
        Paise::create(['code' => 'BD','name' => 'BANGLADESH']);
        Paise::create(['code' => 'BB','name' => 'BARBADOS']);
        Paise::create(['code' => 'BE','name' => 'BÉLGICA']);
        Paise::create(['code' => 'BZ','name' => 'BELICE']);
        Paise::create(['code' => 'BJ','name' => 'BENÍN']);
        Paise::create(['code' => 'BM','name' => 'BERMUDAS']);
        Paise::create(['code' => 'BY','name' => 'BIELORRUSIA']);
        Paise::create(['code' => 'BO','name' => 'BOLIVIA']);
        Paise::create(['code' => 'BA','name' => 'BOSNIA-HERZEGOVINA']);
        Paise::create(['code' => 'BW','name' => 'BOTSUANA']);
        Paise::create(['code' => 'BV','name' => 'ISLA BOUVET']);
        Paise::create(['code' => 'BR','name' => 'BRASIL']);
        Paise::create(['code' => 'BN','name' => 'BRUNÉI']);
        Paise::create(['code' => 'BG','name' => 'BULGARIA']);
        Paise::create(['code' => 'BF','name' => 'BURKINA FASO']);
        Paise::create(['code' => 'BI','name' => 'BURUNDI']);
        Paise::create(['code' => 'BT','name' => 'BUTÁN']);
        Paise::create(['code' => 'CV','name' => 'REPÚBLICA DE CABO VERDE']);
        Paise::create(['code' => 'KY','name' => 'ISLAS CAIMÁN']);
        Paise::create(['code' => 'KH','name' => 'CAMBOYA']);
        Paise::create(['code' => 'CM','name' => 'CAMERÚN']);
        Paise::create(['code' => 'CA','name' => 'CANADÁ']);
        Paise::create(['code' => 'CF','name' => 'REPÚBLICA CENTROAFRICANA']);
        Paise::create(['code' => 'CC','name' => 'ISLA COCOS']);
        Paise::create(['code' => 'CO','name' => 'COLOMBIA']);
        Paise::create(['code' => 'KM','name' => 'COMORAS']);
        Paise::create(['code' => 'CG','name' => 'CONGO']);
        Paise::create(['code' => 'CD','name' => 'REPÚBLICA ZAIRE']);
        Paise::create(['code' => 'CK','name' => 'ISLAS COOK']);
        Paise::create(['code' => 'KP','name' => 'COREA DEL NORTE']);
        Paise::create(['code' => 'KR','name' => 'COREA DEL SUR']);
        Paise::create(['code' => 'CI','name' => 'COSTA DE MARFIL']);
        Paise::create(['code' => 'CR','name' => 'COSTA RICA']);
        Paise::create(['code' => 'HR','name' => 'CROACIA']);
        Paise::create(['code' => 'CU','name' => 'CUBA']);
        Paise::create(['code' => 'TD','name' => 'CHAD']);
        Paise::create(['code' => 'CZ','name' => 'REPÚBLICA CHECA']);
        Paise::create(['code' => 'CL','name' => 'CHILE']);
        Paise::create(['code' => 'CN','name' => 'CHINA']);
        Paise::create(['code' => 'CY','name' => 'CHIPRE']);
        Paise::create(['code' => 'DK','name' => 'DINAMARCA']);
        Paise::create(['code' => 'DM','name' => 'DOMINICA']);
        Paise::create(['code' => 'DO','name' => 'REPÚBLICA DOMINICANA']);
        Paise::create(['code' => 'EC','name' => 'ECUADOR']);
        Paise::create(['code' => 'EG','name' => 'EGIPTO']);
        Paise::create(['code' => 'AE','name' => 'EMIRATOS ÁRABES UNIDOS']);
        Paise::create(['code' => 'ER','name' => 'ERITREA']);
        Paise::create(['code' => 'SK','name' => 'ESLOVAQUIA']);
        Paise::create(['code' => 'SI','name' => 'ESLOVENIA']);
        Paise::create(['code' => 'ES','name' => 'ESPAÑA']);
        Paise::create(['code' => 'US','name' => 'ESTADOS UNIDOS DE AMÉRICA']);
        Paise::create(['code' => 'EE','name' => 'ESTONIA']);
        Paise::create(['code' => 'ET','name' => 'ETIOPÍA']);
        Paise::create(['code' => 'FO','name' => 'ISLAS FEROE']);
        Paise::create(['code' => 'PH','name' => 'FILIPINAS']);
        Paise::create(['code' => 'FI','name' => 'FINLANDIA']);
        Paise::create(['code' => 'FJ','name' => 'FIYI']);
        Paise::create(['code' => 'FR','name' => 'FRANCIA']);
        Paise::create(['code' => 'GA','name' => 'GABÓN']);
        Paise::create(['code' => 'GM','name' => 'GAMBIA']);
        Paise::create(['code' => 'GE','name' => 'GEORGIA']);
        Paise::create(['code' => 'GS','name' => 'GEORGIA DEL SUR']);
        Paise::create(['code' => 'GH','name' => 'GHANA']);
        Paise::create(['code' => 'GI','name' => 'GIBRALTAR']);
        Paise::create(['code' => 'GD','name' => 'GRANADA']);
        Paise::create(['code' => 'GR','name' => 'GRECIA']);
        Paise::create(['code' => 'GL','name' => 'GROENLANDIA']);
        Paise::create(['code' => 'GU','name' => 'GUAM']);
        Paise::create(['code' => 'GT','name' => 'GUATEMALA']);
        Paise::create(['code' => 'GG','name' => 'ISLA GUERNESEY']);
        Paise::create(['code' => 'GN','name' => 'GUINEA']);
        Paise::create(['code' => 'GQ','name' => 'GUINEA ECUATORIAL']);
        Paise::create(['code' => 'GW','name' => 'GUINEA-BISSAU']);
        Paise::create(['code' => 'GY','name' => 'GUYANA']);
        Paise::create(['code' => 'HT','name' => 'HAITÍ']);
        Paise::create(['code' => 'HM','name' => 'ISLAS HEARD Y MCDONALD']);
        Paise::create(['code' => 'HN','name' => 'HONDURAS']);
        Paise::create(['code' => 'HK','name' => 'HONG-KONG']);
        Paise::create(['code' => 'HU','name' => 'HUNGRÍA']);
        Paise::create(['code' => 'IN','name' => 'INDIA']);
        Paise::create(['code' => 'ID','name' => 'INDONESIA']);
        Paise::create(['code' => 'IR','name' => 'IRÁN']);
        Paise::create(['code' => 'IQ','name' => 'IRAQ']);
        Paise::create(['code' => 'IE','name' => 'IRLANDA']);
        Paise::create(['code' => 'IM','name' => 'ISLA DE MAN']);
        Paise::create(['code' => 'IS','name' => 'ISLANDIA']);
        Paise::create(['code' => 'IL','name' => 'ISRAEL']);
        Paise::create(['code' => 'IT','name' => 'ITALIA']);
        Paise::create(['code' => 'JM','name' => 'JAMAICA']);
        Paise::create(['code' => 'JP','name' => 'JAPÓN']);
        Paise::create(['code' => 'JE','name' => 'ISLA JERSEY']);
        Paise::create(['code' => 'JO','name' => 'JORDANIA']);
        Paise::create(['code' => 'KZ','name' => 'KAZAJSTÁN']);
        Paise::create(['code' => 'KE','name' => 'KENIA']);
        Paise::create(['code' => 'KG','name' => 'KIRGUISTÁN']);
        Paise::create(['code' => 'KI','name' => 'KIRIBATI']);
        Paise::create(['code' => 'KW','name' => 'KUWAIT']);
        Paise::create(['code' => 'LA','name' => 'LAOS']);
        Paise::create(['code' => 'LS','name' => 'LESOTHO']);
        Paise::create(['code' => 'LV','name' => 'LETONIA']);
        Paise::create(['code' => 'LB','name' => 'LÍBANO']);
        Paise::create(['code' => 'LR','name' => 'LIBERIA']);
        Paise::create(['code' => 'LY','name' => 'LIBIA']);
        Paise::create(['code' => 'LI','name' => 'LIECHTENSTEIN']);
        Paise::create(['code' => 'LT','name' => 'LITUANIA']);
        Paise::create(['code' => 'LU','name' => 'LUXEMBURGO']);
        Paise::create(['code' => 'XG','name' => 'LUXEMBURGO']);
        Paise::create(['code' => 'MO','name' => 'MACAO']);
        Paise::create(['code' => 'MK','name' => 'MACEDONIA']);
        Paise::create(['code' => 'MG','name' => 'MADAGASCAR']);
        Paise::create(['code' => 'MY','name' => 'MALASIA']);
        Paise::create(['code' => 'MW','name' => 'MALAWI']);
        Paise::create(['code' => 'MV','name' => 'MALDIVAS']);
        Paise::create(['code' => 'ML','name' => 'MALI']);
        Paise::create(['code' => 'MT','name' => 'MALTA']);
        Paise::create(['code' => 'FK','name' => 'ISLAS MALVINAS']);
        Paise::create(['code' => 'MP','name' => 'ISLAS MARIANAS DEL NORTE']);
        Paise::create(['code' => 'MA','name' => 'MARRUECOS']);
        Paise::create(['code' => 'MH','name' => 'ISLAS MARSHALL']);
        Paise::create(['code' => 'MU','name' => 'MAURICIO']);
        Paise::create(['code' => 'MR','name' => 'MAURITANIA']);
        Paise::create(['code' => 'YT','name' => 'MAYOTTE']);
        Paise::create(['code' => 'UM','name' => 'ISLAS ALEJADAS DE LOS EE.UU']);
        Paise::create(['code' => 'MX','name' => 'MÉXICO']);
        Paise::create(['code' => 'FM','name' => 'MICRONESIA']);
        Paise::create(['code' => 'MD','name' => 'MOLDAVIA']);
        Paise::create(['code' => 'MC','name' => 'MÓNACO']);
        Paise::create(['code' => 'MN','name' => 'MONGOLIA']);
        Paise::create(['code' => 'MS','name' => 'MONTSERRAT']);
        Paise::create(['code' => 'MZ','name' => 'MOZAMBIQUE']);
        Paise::create(['code' => 'MM','name' => 'MYANMAR']);
        Paise::create(['code' => 'NA','name' => 'NAMIBIA']);
        Paise::create(['code' => 'NR','name' => 'NAURU']);
        Paise::create(['code' => 'CX','name' => 'ISLA NAVIDAD']);
        Paise::create(['code' => 'NP','name' => 'NEPAL']);
        Paise::create(['code' => 'NI','name' => 'NICARAGUA']);
        Paise::create(['code' => 'NE','name' => 'NÍGER']);
        Paise::create(['code' => 'NG','name' => 'NIGERIA']);
        Paise::create(['code' => 'NU','name' => 'ISLA NIUE']);
        Paise::create(['code' => 'NF','name' => 'ISLA NORFOLK']);
        Paise::create(['code' => 'NO','name' => 'NORUEGA']);
        Paise::create(['code' => 'NZ','name' => 'NUEVA ZELANDA']);
        Paise::create(['code' => 'IO','name' => 'ISLA BRITANICA CHAGOS']);
        Paise::create(['code' => 'OM','name' => 'OMÁN']);
        Paise::create(['code' => 'NL','name' => 'PAÍSES BAJOS']);
        Paise::create(['code' => 'PK','name' => 'PAKISTÁN']);
        Paise::create(['code' => 'PW','name' => 'PALAU']);
        Paise::create(['code' => 'PA','name' => 'PANAMÁ']);
        Paise::create(['code' => 'PG','name' => 'PAPÚA NUEVA GUINEA']);
        Paise::create(['code' => 'PY','name' => 'PARAGUAY']);
        Paise::create(['code' => 'PE','name' => 'PERÚ']);
        Paise::create(['code' => 'PN','name' => 'PITCAIRN']);
        Paise::create(['code' => 'PF','name' => 'POLINESIA FRANCESA']);
        Paise::create(['code' => 'PL','name' => 'POLONIA']);
        Paise::create(['code' => 'PT','name' => 'PORTUGAL']);
        Paise::create(['code' => 'PR','name' => 'PUERTO RICO']);
        Paise::create(['code' => 'QA','name' => 'QATAR']);
        Paise::create(['code' => 'GB','name' => 'REINO UNIDO']);
        Paise::create(['code' => 'RW','name' => 'RUANDA']);
        Paise::create(['code' => 'RO','name' => 'RUMANÍA']);
        Paise::create(['code' => 'RU','name' => 'RUSIA']);
        Paise::create(['code' => 'SB','name' => 'ISLAS SALOMÓN']);
        Paise::create(['code' => 'SV','name' => 'EL SALVADOR']);
        Paise::create(['code' => 'WS','name' => 'SAMOA']);
        Paise::create(['code' => 'AS','name' => 'SAMOA AMERICANA']);
        Paise::create(['code' => 'KN','name' => 'SAN CRISTÓBAL Y NIEVES']);
        Paise::create(['code' => 'SM','name' => 'SAN MARINO']);
        Paise::create(['code' => 'PM','name' => 'SAN PEDRO Y MIQUELÓN']);
        Paise::create(['code' => 'VC','name' => 'SAN VICENTE Y LAS GRANADINAS']);
        Paise::create(['code' => 'SH','name' => 'SANTA ELENA']);
        Paise::create(['code' => 'LC','name' => 'SANTA LUCÍA']);
        Paise::create(['code' => 'ST','name' => 'SANTO TOMÉ Y PRÍNCIPE']);
        Paise::create(['code' => 'SN','name' => 'SENEGAL']);
        Paise::create(['code' => 'CS','name' => 'SERBIA Y MONTENEGRO']);
        Paise::create(['code' => 'SC','name' => 'SEYCHELLES']);
        Paise::create(['code' => 'SL','name' => 'SIERRA LEONA']);
        Paise::create(['code' => 'SG','name' => 'SINGAPUR']);
        Paise::create(['code' => 'SY','name' => 'SIRIA']);
        Paise::create(['code' => 'SO','name' => 'SOMALIA']);
        Paise::create(['code' => 'LK','name' => 'SRI LANKA']);
        Paise::create(['code' => 'SZ','name' => 'SUAZILANDIA']);
        Paise::create(['code' => 'ZA','name' => 'SUDÁFRICA']);
        Paise::create(['code' => 'SD','name' => 'SUDÁN']);
        Paise::create(['code' => 'SE','name' => 'SUECIA']);
        Paise::create(['code' => 'CH','name' => 'SUIZA']);
        Paise::create(['code' => 'SR','name' => 'SURINAM']);
        Paise::create(['code' => 'TH','name' => 'TAILANDIA']);
        Paise::create(['code' => 'TW','name' => 'TAIWÁN']);
        Paise::create(['code' => 'TZ','name' => 'TANZANIA']);
        Paise::create(['code' => 'TJ','name' => 'TAYIKISTÁN']);
        Paise::create(['code' => 'PS','name' => 'CISJORDANIA_GAZA']);
        Paise::create(['code' => 'TF','name' => 'TIERRAS AUSTRALES FRANCESAS']);
        Paise::create(['code' => 'TL','name' => 'TIMOR LESTE']);
        Paise::create(['code' => 'TG','name' => 'TOGO']);
        Paise::create(['code' => 'TK','name' => 'ISLAS TOKELAU']);
        Paise::create(['code' => 'TO','name' => 'TONGA']);
        Paise::create(['code' => 'TT','name' => 'TRINIDAD Y TOBAGO']);
        Paise::create(['code' => 'TN','name' => 'TÚNEZ']);
        Paise::create(['code' => 'TC','name' => 'ISLAS TURCAS Y CAICOS']);
        Paise::create(['code' => 'TM','name' => 'TURKMENISTÁN']);
        Paise::create(['code' => 'TR','name' => 'TURQUÍA']);
        Paise::create(['code' => 'TV','name' => 'TUVALU']);
        Paise::create(['code' => 'UA','name' => 'UCRANIA']);
        Paise::create(['code' => 'UG','name' => 'UGANDA']);
        Paise::create(['code' => 'UY','name' => 'URUGUAY']);
        Paise::create(['code' => 'UZ','name' => 'UZBEKISTÁN']);
        Paise::create(['code' => 'VU','name' => 'VANUATU']);
        Paise::create(['code' => 'VA','name' => 'VATICANO']);
        Paise::create(['code' => 'VE','name' => 'VENEZUELA']);
        Paise::create(['code' => 'VN','name' => 'VIETNAM']);
        Paise::create(['code' => 'VG','name' => 'ISLAS VÍRGENES BRITÁNICAS']);
        Paise::create(['code' => 'VI','name' => 'VÍRGENES DE LOS EE.UU, ISLAS']);
        Paise::create(['code' => 'WF','name' => 'ISLAS WALLIS Y FUTUNA']);
        Paise::create(['code' => 'YE','name' => 'YEMEN']);
        Paise::create(['code' => 'DJ','name' => 'YIBUTI']);
        Paise::create(['code' => 'ZM','name' => 'ZAMBIA']);
        Paise::create(['code' => 'ZW','name' => 'ZIMBABUE']);
        Paise::create(['code' => 'QU','name' => 'OTROS PAÍSES O TERRITORIOS NO RELACIONADOS']);
        Paise::create(['code' => 'XB','name' => 'BANCO CENTRAL EUROPEO']);
        Paise::create(['code' => 'XU','name' => 'INSTITUCIONES DE LA UNIÓN EUROPEA']);
        Paise::create(['code' => 'XN','name' => 'ORGANISMOS INTERNACIONALES']);
    }
}
